INSERT INTO programa_anuales(nombre,id_aprobado) VALUES('PROGRAMA ANUAL DE SEGURIDAD Y SALUD EN EL TRABAJO 2020 ECOBESA',1);
INSERT INTO programa_anuales(nombre,id_aprobado) VALUES('PROGRAMA ANUAL DE SEGURIDAD Y SALUD EN EL TRABAJO 2020 ECOBESA',2);
INSERT INTO programa_anuales(nombre,id_aprobado) VALUES('PROGRAMA ANUAL DE SEGURIDAD Y SALUD EN EL TRABAJO 2020 ECOBESA',3);